services:
  afl-parity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: afl-parity-container
    volumes:
      - ./output:/afl-parity/output
      - ./.logs:/afl-parity/.logs
      # timezone linking
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro
