[project]
name = "afl-parity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "pillow>=12.3.0",
    "requests>=2.32.3",
    "uv>=0.6.5",
]

[dependency-groups]
dev = [
    "ruff>=0.9.9",
    "pytest>=8.3.5",
    "ty>=0.0.61",
]
